import { writable } from 'svelte/store';

export const mapConfig = writable({
  "title": "How do European pupils perform in mathematics?",
  "subtitle": "With 508 points in the 2025 PISA test in maths, Estonia tops the EU rankings, while Bulgaria is last with 405 points. The EU-wide average stands at around 460 points, close to the OECD average of 463.",
  "colourSchemeClasses": 7,
  "data": "country,id,value,extraInfo,text_content,link_text,link_url_target,audio_url_1,audio_url_2,audio_url_3,image_url_source,image_url_target,video_url\nAustria,AT,477,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nBelgium,BE,480,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nBulgaria,BG,405,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nCroatia,HR,455,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nCyprus,CY,412,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nCzechia,CZ,477,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nDenmark,DK,471,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nEstonia,EE,508,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nFinland,FI,469,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nFrance,FR,458,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nGermany,DE,464,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nGreece,EL,424,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nHungary,HU,459,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nIreland,IE,480,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nItaly,IT,468,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nLatvia,LV,460,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nLithuania,LT,470,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nLuxembourg,LU,458,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nMalta,MT,439,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nNetherlands,NL,483,false,\"Caution: one or more PISA sampling standards were not met; interpret the estimate with care.\",OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nPoland,PL,484,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nPortugal,PT,460,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nRomania,RO,419,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nSlovakia,SK,469,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nSlovenia,SI,460,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nSpain,ES,457,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,\nSweden,SE,464,false,,OECD PISA 2025,https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html,,,,,,",
  "parsedData": [
    {
      "country": "Austria",
      "id": "AT",
      "value": 477,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Belgium",
      "id": "BE",
      "value": 480,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Bulgaria",
      "id": "BG",
      "value": 405,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Croatia",
      "id": "HR",
      "value": 455,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Cyprus",
      "id": "CY",
      "value": 412,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Czechia",
      "id": "CZ",
      "value": 477,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Denmark",
      "id": "DK",
      "value": 471,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Estonia",
      "id": "EE",
      "value": 508,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Finland",
      "id": "FI",
      "value": 469,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "France",
      "id": "FR",
      "value": 458,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Germany",
      "id": "DE",
      "value": 464,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Greece",
      "id": "EL",
      "value": 424,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Hungary",
      "id": "HU",
      "value": 459,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Ireland",
      "id": "IE",
      "value": 480,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Italy",
      "id": "IT",
      "value": 468,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Latvia",
      "id": "LV",
      "value": 460,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Lithuania",
      "id": "LT",
      "value": 470,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Luxembourg",
      "id": "LU",
      "value": 458,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Malta",
      "id": "MT",
      "value": 439,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Netherlands",
      "id": "NL",
      "value": 483,
      "extraInfo": false,
      "text_content": "Caution: one or more PISA sampling standards were not met; interpret the estimate with care.",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Poland",
      "id": "PL",
      "value": 484,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Portugal",
      "id": "PT",
      "value": 460,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Romania",
      "id": "RO",
      "value": 419,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Slovakia",
      "id": "SK",
      "value": 469,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Slovenia",
      "id": "SI",
      "value": 460,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Spain",
      "id": "ES",
      "value": 457,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Sweden",
      "id": "SE",
      "value": 464,
      "extraInfo": false,
      "text_content": "",
      "link_text": "OECD PISA 2025",
      "link_url_target": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    }
  ],
  "datasetType": "values",
  "datasetUnit": "fullNumbers",
  "percentRounded": false,
  "colourSchemeType": "sequential",
  "colourScheme": "red-purple",
  "colourSchemeReverse": false,
  "headlineAvailable": true,
  "subheadlineAvailable": true,
  "tooltipAvailable": true,
  "scaleBarAvailable": true,
  "overrideScaleValues": true,
  "legendAvailable": true,
  "textSourceAvailable": true,
  "textSourceDescription": "Source",
  "textSource": "OECD (2026)",
  "textNoteAvailable": true,
  "textNoteDescription": "Note",
  "textNote": "PISA assesses 15-year-old pupils' ability to apply their knowledge and skills to tackle real-life challenges. The OECD average mathematics score fell to 463 points in PISA 2025, nine points below 2022. Compared with 2015, the OECD average has declined by 22 points, from 485 to 463. The EU average of 460 points shown here is calculated as the unweighted mean of the 27 member states' scores,  and does not constitute an official OECD aggregate for the EU.",
  "textDataAccessAvailable": true,
  "linkDataAccessDescription": "Access the data",
  "linkDataAccess": "https://www.oecd.org/de/publications/pisa-2025-ergebnisse-band-i-auszugsweise-ubersetzung_1562a447-de.html",
  "legend1": "No data available",
  "legend1Color": "#E0E0E0",
  "colorBarFirstValue": "400",
  "colorBarLastValue": "510",
  "customUnitLabelAvailable": false,
  "customUnitLabel": "",
  "tooltipExtraInfoLabel": "Click here",
  "translate": {
    "title": "How do European pupils perform in mathematics?",
    "subtitle": "With 508 points in the 2025 PISA test in maths, Estonia tops the EU rankings, while Bulgaria is last with 405 points. The EU-wide average stands at around 460 points, close to the OECD average of 463.",
    "textNoteDescription": "Note",
    "textNote": "PISA assesses 15-year-old pupils' ability to apply their knowledge and skills to tackle real-life challenges. The OECD average mathematics score fell to 463 points in PISA 2025, nine points below 2022. Compared with 2015, the OECD average has declined by 22 points, from 485 to 463. The EU average of 460 points shown here is calculated as the unweighted mean of the 27 member states' scores,  and does not constitute an official OECD aggregate for the EU.",
    "textSourceDescription": "Source",
    "textSource": "OECD (2026)",
    "linkDataAccessDescription": "Access the data",
    "legend1": "No data available",
    "tooltipExtraInfoLabel": "Click here",
    "extraInfo_NL": "Caution: one or more PISA sampling standards were not met; interpret the estimate with care."
  },
  "clusters": [],
  "colorScale": null,
  "extraInfo_NL": "Caution: one or more PISA sampling standards were not met; interpret the estimate with care."
});
